name = "PartialRejectionSampling"
uuid = "462d7af4-98e5-4ce7-aadc-1f465a3a6705"
authors = ["Guillaume Gautier <guillaume.gga@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
